import copy
import random
from dataclasses import asdict, dataclass, field, fields

from core.genome.base_genome import Genome as BaseGenome


RPG_STAT_METADATA = {
    "range": (3, 18),
    "roll": "3d6",
}


@dataclass
class Genome(BaseGenome):
    """Six inherited RPG attributes initially generated by rolling 3d6."""

    strength: int = field(default=10, metadata=RPG_STAT_METADATA)
    dexterity: int = field(default=10, metadata=RPG_STAT_METADATA)
    constitution: int = field(default=10, metadata=RPG_STAT_METADATA)
    intelligence: int = field(default=10, metadata=RPG_STAT_METADATA)
    wisdom: int = field(default=10, metadata=RPG_STAT_METADATA)
    charisma: int = field(default=10, metadata=RPG_STAT_METADATA)

    def __post_init__(self):
        for genome_field in fields(self):
            value = getattr(self, genome_field.name)
            lo, hi = genome_field.metadata["range"]
            if not isinstance(value, int) or isinstance(value, bool):
                raise TypeError(
                    f"{genome_field.name} must be an integer, got {type(value).__name__}"
                )
            if not lo <= value <= hi:
                raise ValueError(
                    f"{genome_field.name}={value} outside {lo}-{hi}"
                )

    @staticmethod
    def _roll_3d6() -> int:
        return sum(random.randint(1, 6) for _ in range(3))

    @classmethod
    def random(cls) -> "Genome":
        scores = {
            genome_field.name: cls._roll_3d6() for genome_field in fields(cls)
        }
        return cls(**scores)

    def as_dict(self) -> dict[str, int]:
        return asdict(self)

    def from_dict(self, data: dict[str, int]) -> "Genome":
        return Genome(**data)

    def as_string(self) -> str:
        stat_lines = "\n".join(
            f"  {genome_field.name.title()} value: {getattr(self, genome_field.name)}"
            for genome_field in fields(self)
        )
        return (
            "=== Your Traits ===\n"
            "RPG attributes (each score is determined by 3d6; range 3-18)\n"
            f"{stat_lines}"
        )

    @staticmethod
    def clamp(value: int, lo: int, hi: int) -> int:
        return max(lo, min(hi, value))

    def mutate(self, rate: float = 0.5, **_kwargs) -> "Genome":
        child = copy.deepcopy(self)
        for genome_field in fields(child):
            if random.random() >= rate:
                continue
            lo, hi = genome_field.metadata["range"]
            value = getattr(child, genome_field.name)
            value += random.choice([-1, 0, 1])
            setattr(child, genome_field.name, self.clamp(value, lo, hi))
        return child
